version: 2.1

executors:
  docker-node:
    docker:
      - image: circleci/node:11
  docker-thesis-buildpack:
    docker:
      - image: thesisco/docker-buildpack:bionic

orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4

jobs:
  test_client:
    executor: docker-node
    working_directory: ~/project/client
    steps:
      - checkout:
          path: ~/project

      # Download and cache dependencies.
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to restore cache.
            - v1-client-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-client-npm-deps-{{ .Branch }}-
            - v1-client-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-client-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Run tests.
      - run:
          name: Run NPM tests
          command: npm run test:setup && npm run test

  test_tbtc_helpers:
    executor: docker-node
    working_directory: ~/project/lib/tbtc-helpers
    steps:
      - checkout:
          path: ~/project

      # Download and cache dependencies.
      - restore_cache:
          keys:
            # When lock file changes, use increasingly general patterns to restore cache.
            - v1-helpers-npm-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-helpers-npm-deps-{{ .Branch }}-
            - v1-helpers-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-helpers-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Run tests.
      - run:
          name: Run NPM tests
          command: npm test

  build_dapp:
    executor: docker-thesis-buildpack
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - run:
          name: Set Gcloud Auth
          command: |
            echo $GCLOUD_SERVICE_KEY_GET_BUCKET_OBJECT > ~/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      - run:
          name: Fetch contract artifacts
          command: |
            ./scripts/fetch-contracts.sh
      - run:
          name: Run Docker build
          command: |
            docker build -t build --target build .
            docker build -t $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/tbtc-dapp .
      - run:
          name: Save tbtc-dapp image
          command: |
            mkdir -p /tmp/tbtc-dapp/docker-images/
            docker save -o /tmp/tbtc-dapp/docker-images/tbtc-dapp.tar $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/tbtc-dapp
      - persist_to_workspace:
          root: /tmp/tbtc-dapp
          paths:
            - docker-images

  publish_dapp:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: /tmp/tbtc-dapp
      - run:
          name: Load tbtc-dapp image
          command: |
            docker load -i /tmp/tbtc-dapp/docker-images/tbtc-dapp.tar
      - gcp-gcr/gcr-auth:
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE_A
          # This param doesn't actually set anything, leaving here as a reminder to check when they fix it.
          gcloud-service-key: GCLOUD_SERVICE_KEY
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: $GCR_REGISTRY_URL
          image: tbtc-dapp
          tag: latest

workflows:
  version: 2
  client:
    jobs:
      - test_client
  tbtc_helpers:
    jobs:
      - test_tbtc_helpers
  dapp_keep_dev:
    jobs:
      - build_dapp:
          context: keep-dev
      - publish_dapp:
          filters:
            branches:
              only: master
          context: keep-dev
          requires:
            - build_dapp
  dapp_keep_test:
    jobs:
      - keep_test_approval:
          type: approval
          # filters:
          #   tags:
          #     only: /^v.*/
          #   branches:
          #     ignore: /.*/
      - build_dapp:
          # filters:
          #   tags:
          #     only: /^v.*/
          #   branches:
          #     ignore: /.*/
          context: keep-test
          requires:
            - keep_test_approval
      - publish_dapp:
          # filters:
          #   tags:
          #     only: /^v.*/
          #   branches:
          #     ignore: /.*/
          context: keep-test
          requires:
            - build_dapp
